export const COLOR_PALETTE = {
  PRIMARY: '#2c4351',
  PRIMARY_DARKER: '#031c29',
  PRIMARY_LIGHTER: '#576e7d',
  SECONDARY: '#e5ff3e',
  SECONDARY_DARKER: '#afcc00',
  SECONDARY_LIGHTER: '#ffff76',
  BASE: '#DDD',
  WHITE: '#ffffff'
}